### PR TITLE
Optimize py3-celery container build time and size

### LINKED ISSUE #639: Python environments should be defined in a single requirements.txt file for each Celery image
Currently, the Python environment inside each Celery image is defined in [Each of the 'install_*****_rodan_jobs'](https://github.com/DDMAL/Rodan/tree/develop/scripts) scripts by sequentially installing the contents of each `requirements.txt` folder for that particular image. This is a holdover from when all the jobs were in their own github repositories, and is difficult to maintain.

Every image we maintain that has its own python environment should have its own `requirements.txt`, located in the same directory as its dockerfile. These should not be written to by people who are working on jobs - they should conform to what the environment dictates. These requirements files could be generated by simply performing a `pip freeze` inside every docker container, and then rewriting the `install_*****_rodan_jobs` scripts accordingly.

### LINKED ISSUE #737: After py3_migration, rodan-main fails to import `pika` module despite try-catch block
This is the last thing in the way of getting py3-migration running. Despite the presence of a try-catch block to ignore import errors in `rodan-main/code/rodan/jobs/hpc_fast_trainer/hpc_fast_trainer.py`, rodan-main still hits the following error when trying to load jobs:

```
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |     self.fetch_command(subcommand).run_from_argv(self.argv)
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |     self.execute(*args, **cmd_options)
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |     output = self.handle(*args, **options)
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 227, in handle
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |     self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/sql.py", line 53, in emit_post_migrate_signal
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |     **kwargs
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |   File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 193, in send
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |     for receiver in self._live_receivers(sender)
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |   File "/code/Rodan/rodan/models/__init__.py", line 81, in update_rodan_jobs
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |     import rodan.jobs.load  # noqa
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |   File "/code/Rodan/rodan/jobs/load.py", line 481, in <module>
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |     module_loader(package_name, set_version)  # RodanTaskType will update `job_list`
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |   File "/code/Rodan/rodan/jobs/__init__.py", line 13, in module_loader
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    |     raise ImportError("Trouble loading module {0}.\nMessage: {1}".format(name, e))
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    | ImportError: Trouble loading module rodan.jobs.hpc_fast_trainer.
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    | Message: Trouble loading module rodan.jobs.hpc_fast_trainer.hpc_fast_trainer.
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    | Message: No module named pika
rodan_rodan-main.1.iyndm7a3i8r2@staging-rodan-gpu-swarm    | Broken pipe

```

Not sure how it's possible that it's still trying to import it - especially since this was working earlier this week. Strange.

### PR DESCRIPTION
**Pull request by p42ul**
Fixes #737.
Fixes #639.

### CODE REVIEW

**Comment by p42ul** [comment]
Fixes #737

**Comment by p42ul** [comment]
Fixes #639.

**Review by timothydereuse — CHANGES_REQUESTED** [review]
Excellent, good simplifications. When cloning `pixel-wrapper` or `neon-wrapper` I would either hard-code it to be the `develop` branch or point to a specific commit. Not sure what would be easiest. But afaik the `BRANCHES` arg is not being effectively used in our build process - i.e. we only ever build on develop, really - and we haven't worked out what the `master` / `main` branches of `neon-wrapper` and `pixel-wrapper` even mean yet.

**Comment by p42ul** [comment]
Benchmarks:


**Original container**
```
 /usr/bin/time docker build \
--tag ddmal/rodan-python3-celery:develop \
--file ./python3-celery/Dockerfile \
--no-cache \
.

...

Successfully built a7afe0dfca53
Successfully tagged ddmal/rodan-python3-celery:develop
3.85user 1.94system 24:02.59elapsed 0%CPU (0avgtext+0avgdata 65580maxresident)k
512inputs+0outputs (2major+12942minor)pagefaults 0swaps
```
Size: 9.14GB

**New container**
```
tbd
```

**Review by p42ul — COMMENTED** [review]
OK, I've pinned the `BRANCH` argument to develop, though it can be overridden at build time.

**Review by timothydereuse — APPROVED** [review]

**Pull request merged**
