### PR TITLE
Wait for the user to stop typing before making a search request

### PR DESCRIPTION
**Pull request by jackyyzhang03**
Resolves: (#925)
- [x] I passed the docker hub test, and images can be built successfully.
- [x] I passed the GitHub CI test, so rodan functionalities and jobs work.

(Describe the changes you've made and the purpose of this PR)
- Set a short timer before making a request and reset the timer each time a keystroke is made so that a request is made only when the user is finished typing

### CODE REVIEW

**Comment by fujinaga** [comment]
Please avoid using unnamed magic numbers, in this case: "500". Give it an easily understandable variable name. The delay time should ideally be user tested (please make a separate issue). There may be literature on this (e.g., for autocompletion).

**Comment by cadagong** [comment]
I started a discussion about this and other potential solutions inside issue #925!

**Comment by jackyyzhang03** [comment]
I wasn't able to find any academic papers on this topic, though I might not using the correct search terms. I did find that the numbers mentioned in developer forums typically ranges between 300 ms to 500 ms and the Doherty Threshold suggests that the requirement for computer response time is 400 ms, so I've changed the delay to reflect this.

Should I make an issue for user testing right now, or hold off on it until the changes have been pushed to staging?

**Comment by fujinaga** [comment]
You can make the issue for testing now so that we won't forget. Thank you.

**Review by cadagong — APPROVED** [review]
Looks great!!

**Pull request merged**
