### PR TITLE
Clean up our Dockerfiles

### LINKED ISSUE #718: Rodan login screen submits HTTP token auth request instead of HTTPS when SSL isn't terminated in container
**Issue:**
When `"SERVER_HTTPS": true` in `nginx/config/configuration.json`, but `TLS: 0` in the `docker-compose.yml` file (the server is running in HTTPS mode but not terminating its own SSL), the Rodan login button doesn't work properly, as it tries to log in using an HTTP URL. This fails with a mixed media content warning.

**Background:**
I've been working to try to standardize our SSL termination strategy, and part of that has involved moving all of our certificates to one set of machines for ease of certificate management and renewal. However, Rodan was originally only configured for two modes of operation: dev, where everything is unencrypted HTTP and the server is hosted on `localhost`, and staging/prod, where the stack controls its own SSL termination and the server has a domain name that it will use alongside HTTPS. I attempted to add a third mode, where the stack would control everything in staging/prod but SSL termination, but I ran into this issue along the way; it seems like it wasn't quite as simple as just changing the config files.

**Hypothesis**
I can't find any one location where this URL is stored in plain text. My assumption is therefore that (since it doesn't fail when SSL is terminated in the stack) it's using the protocol that the site is accessed with in order to connect to the API. However, since we're passing along HTTP from the edge router, the webapp is ignoring the URL that is otherwise entirely HTTPS and connecting with HTTP instead. Through some research, I've found that the site may be ignoring the `X-Forwarded-Proto` header, which should contain the HTTPS info that we need. However, I'm not sure how to implement that into Rodan, or even what part to look at.

### PR DESCRIPTION
**Pull request by kqct**
Resolves #718, superceding #1013 and #1014 
- [ ] I passed the docker hub test, and images can be built successfully.
- [ ] I passed the GitHub CI test, so rodan functionalities and jobs work.

This PR encompasses a couple of changes that I wasn't quite able to split apart:
- Created a new Docker Compose file that uses the images I built, as well as removing references to old hpc-rabbitmq, flower
- Rewrote iipsrv Dockerfile, reducing built image size by >50%
- Edited nginx Dockerfile, removing old unnecessary configuration files and keys and simplifying the run command
- Edited nginx configuration, removing SSL as a builtin option
- Redid Rodan client, moving it to its own Docker image which builds and runs the client code on its own.
- Modified Rodan client to not assume port, allowing for sane HTTPS config (this changes how Rodan client is run, @sabrina0822)

### CODE REVIEW

**Comment by timothydereuse** [comment]
fantastic work, thank you! i'd like to get this in ASAP but since production is currently down for reasons that seem unrelated to the docker images themselves I'm not sure when the best time would be.

**Comment by timothydereuse** [comment]
Docker building thru github actions doesn't seem to be working lately. can someone (@kqct maybe) confirm that this built successfully and works locally? if so, i'd like to merge it in this week now that production's back up.

**Comment by sabrina0822** [comment]
Just checked the docker build, it seems to have failed because of the node version. Going to look into it a bit. 
```
2023-08-08T00:41:26Z > [builder 5/8] RUN yarn install --inline-builds && yarn cache clean:
2023-08-08T00:41:26Z #15 0.506 yarn install v1.22.19
2023-08-08T00:41:26Z #15 0.708 [1/5] Validating package.json...
2023-08-08T00:41:26Z #15 0.718 error rodan-client@0.20.0: The engine "node" is incompatible with this module. Expected version "12.22.x". Got "14.21.1"
2023-08-08T00:41:26Z #15 0.732 error Found incompatible module.
2023-08-08T00:41:26Z #15 0.732 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2023-08-08T00:41:26Z ------
2023-08-08T00:41:26Z ERROR: failed to solve: executor failed running [/bin/sh -c yarn install --inline-builds && yarn cache clean]: exit code: 1
2023-08-08T00:41:26Z build hook failed! (1)
```

**Comment by timothydereuse** [comment]
@kqct: how should we run / test this locally? using the old `docker-compose` file or the new `compose.yaml` file you've included? should we be referencing the `smaller` tag at all after this is merged in? we (sabrina and i) weren't able to get this running locally, though the images built after she changed the node version

also, how should rodan-client be run for local development under this setup? need to document that as well.

**Comment by sabrina0822** [comment]
I tried running this locally and noticed a few things. 

This branch currently has a `compose.yaml` and a `docker-compose.yml`, I do not think we should have two docker compose files and should only keep the relevant one. The current `compose.yaml` references `ddmal/iipsrv:smaller` however when I tried to run rodan locally it complained that it couldn't find this image --> I'm assuming the image just needs to be pushed on our docker repo. 

I then changed the compose.yaml to use `ddmal/iipsrv:nightly` but when I tried to run the rodan-main container with the start script - `docker compose exec rodan-main /run/start` - the command failed with no error.

**Comment by kqct** [comment]
To answer the questions that have come up:
- the way I ran the project locally was the `compose.yaml` file, which uses the new `rodan-client` image, the new (locally built for testing) `iipsrv` image, and the different `nginx` build
- the `smaller` tag was just my test tag so it wouldn't overlap with `nightly`; it's not necessary to keep
- `rodan-client` is run exactly the same way -- the only thing I did was move it into its own container so that changes to it didn't involve rebuilding multiple containers
- yes, the changes to `nginx` mean that a new ssl setup would have to be put in place. i don't really know how to reference that here
- that's concerning that `rodan-main` failed -- should I try building as well and let you know?

**Review by sabrina0822 — COMMENTED** [review]
This is almost ready to be merged. The main updates that concern local development are: 

-  Now developing on rodan-client is the exact same developing locally
- There are extra steps now when you develop locally which include: 

1. `cp rodan-client/local-dev/COPYconfiguration rodan-client/config/configuration.json`
2. `cp rodan-client/local-dev/CPCONFIGFILE rodan-client/code/src/js/configuration.js`
3. in settings.py change, `SECURE_PROXY_SSL_HEADER = ("HTTP_X_SCHEME", "https")`  to `SECURE_PROXY_SSL_HEADER = ("HTTP_X_SCHEME", "http")`
4. run `make run` or `make run_arm` as usual
5. ALWAYS revert these changes before pushing

- When pushing to production, change line 2 in `rodan-client/config/configuration.json` to: `"SERVER_HOST": "rodan2.simssa.ca"`

I have asked @malajvan to test our arm-compose.yml setup for M1 machines as I think that there still may be some untested lingering problems there.

**Review by sabrina0822 — APPROVED** [review]

**Pull request merged**
