### PR TITLE
Staff distance

### PR DESCRIPTION
**Pull request by MrMondrian**
Resolves: (#ID-of-the-issue)
- [x] I passed the docker hub test, and images can be built successfully.
- [x] I passed the GitHub CI test, so rodan functionalities and jobs work.

Adds a new rodan job that takes in a png of a folio, and returns a json containing the approximate distance between staves, as well as the image scaling factor required to make the distance between staves 64 pixels.

### CODE REVIEW

**Comment by timothydereuse** [comment]
@MrMondrian, can you confirm that this works when running rodan locally, and doesn't break the other containers? The CI tests failed and I'm not sure if it's because they aren't set up to test jobs in the GPU container correctly.

**Comment by MrMondrian** [comment]
Yes it works locally in the container run through the browser, but let’s get the ci test to pass before merging this of course. I can take a look this afternoon after my appointment.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by timothydereuse** [comment]
as long as CI passes, the code looks good to me

**Review by timothydereuse — APPROVED** [review]

**Comment by MrMondrian** [comment]
fixes https://github.com/DDMAL/Rodan/issues/846

**Pull request merged**
